In [1]:
import torch

In [2]:
def activation(x):
    """
     Sigmoid activation function
     Args - x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [3]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

### Features are 5 random normal variables
features = torch.randn((1,5)) # 2 dimensional tensor, 1 row & 5 columns, a row vector which has 5 elements
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1,1))

In [4]:
## Calculate the output of this network using the weights and bias tensors
y = activation(torch.sum(features * weights) + bias) # sigmoid(WX+B)
print(y)
## OR 
y = activation((features * weights).sum() + bias)
print(y)

tensor([[0.1595]])
tensor([[0.1595]])


In [5]:
## Calculate the output of this network using matrix multiplication
f_w = torch.mm(features, weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at /Users/distiller/project/conda/conda-bld/pytorch_1573049287641/work/aten/src/TH/generic/THTensorMath.cpp:197

In [ ]:
## To fix above error we can use torch.view to transform matrix
print(weights)
weights.view(5, 1)

In [ ]:
# output using matmul or mm function of torch
y = activation(torch.mm(features, weights.view(5, 1)) + bias)
print(y)

In [12]:
### Multi layer network example 
# Features are 3 random normal variables
features = torch.randn((1, 3))
print(features)
print(features.shape)

# Define the size of each layer in our network
n_input = features.shape[1] # Number of input units, must match number of input features
n_hidden = 2 # Number of hidden units
n_output = 1 # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
print(W1)
W2 = torch.randn(n_hidden, n_output)
print(W2)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
print(B1)
B2 = torch.randn((1, n_output))
print(B2)

tensor([[-0.8150, -0.9118, -0.0739]])
torch.Size([1, 3])
tensor([[ 1.1056, -0.8667],
        [-0.1373, -0.6714],
        [ 0.9974, -0.1590]])
tensor([[ 0.6804],
        [-0.8669]])
tensor([[ 2.5032, -0.5644]])
tensor([[1.1560]])


In [15]:
# First calculating hidden layer values
h = activation(torch.mm(features, W1) + B1)
print(h)
# Next calculating output using hidden
y = activation(torch.mm(h, W2) + B2)
print(y)

tensor([[0.8394, 0.6826]])
tensor([[0.7568]])


In [17]:
# Converting numpy to torch or vice versa
import numpy as np
a = np.random.rand(4,3)
a

array([[0.80260779, 0.21557835, 0.80846365],
       [0.45002725, 0.62514785, 0.31776107],
       [0.34131766, 0.00879486, 0.79477137],
       [0.81529374, 0.86698804, 0.04417936]])

In [19]:
# converting numpy to torch
b = torch.from_numpy(a)
b

tensor([[0.8026, 0.2156, 0.8085],
        [0.4500, 0.6251, 0.3178],
        [0.3413, 0.0088, 0.7948],
        [0.8153, 0.8670, 0.0442]], dtype=torch.float64)

In [21]:
# converting torch to numpy
b.numpy()

array([[0.80260779, 0.21557835, 0.80846365],
       [0.45002725, 0.62514785, 0.31776107],
       [0.34131766, 0.00879486, 0.79477137],
       [0.81529374, 0.86698804, 0.04417936]])

In [22]:
# Memory is shared between Numpy and Torch tensor
b.mul_(2)

tensor([[1.6052, 0.4312, 1.6169],
        [0.9001, 1.2503, 0.6355],
        [0.6826, 0.0176, 1.5895],
        [1.6306, 1.7340, 0.0884]], dtype=torch.float64)

In [23]:
# Numpy also got changed 
a

array([[1.60521558, 0.43115669, 1.6169273 ],
       [0.9000545 , 1.2502957 , 0.63552213],
       [0.68263532, 0.01758973, 1.58954274],
       [1.63058749, 1.73397608, 0.08835871]])