# Perceptron Algorithm
<img src="images/classification_linear.png">
<img src="images/classification_nd.png">
<img src="images/perceptron.png">

In [7]:
import numpy as np
from numpy import genfromtxt
np.random.seed(42)

In [2]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

In [21]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [23]:
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    for i in range(len(X)):
        y_hat = prediction(X[i], W, b)
        if y[i] - y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i] - y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    return W, b

In [6]:
def trainPerceptronAlogrithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    # randomly selecting weights and bias
    W = np.array(np.random.rand(2, 1))
    b = np.random.rand(1)[0] + x_max
    # These are the solutions lines that get plotted below
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [9]:
data = genfromtxt('perceptron_data.csv', delimiter=',')
data

array([[ 0.78051  , -0.063669 ,  1.       ],
       [ 0.28774  ,  0.29139  ,  1.       ],
       [ 0.40714  ,  0.17878  ,  1.       ],
       [ 0.2923   ,  0.4217   ,  1.       ],
       [ 0.50922  ,  0.35256  ,  1.       ],
       [ 0.27785  ,  0.10802  ,  1.       ],
       [ 0.27527  ,  0.33223  ,  1.       ],
       [ 0.43999  ,  0.31245  ,  1.       ],
       [ 0.33557  ,  0.42984  ,  1.       ],
       [ 0.23448  ,  0.24986  ,  1.       ],
       [ 0.0084492,  0.13658  ,  1.       ],
       [ 0.12419  ,  0.33595  ,  1.       ],
       [ 0.25644  ,  0.42624  ,  1.       ],
       [ 0.4591   ,  0.40426  ,  1.       ],
       [ 0.44547  ,  0.45117  ,  1.       ],
       [ 0.42218  ,  0.20118  ,  1.       ],
       [ 0.49563  ,  0.21445  ,  1.       ],
       [ 0.30848  ,  0.24306  ,  1.       ],
       [ 0.39707  ,  0.44438  ,  1.       ],
       [ 0.32945  ,  0.39217  ,  1.       ],
       [ 0.40739  ,  0.40271  ,  1.       ],
       [ 0.3106   ,  0.50702  ,  1.       ],
       [ 0

In [17]:
X = data[:,:2].reshape(-1,2)
X

array([[ 0.78051  , -0.063669 ],
       [ 0.28774  ,  0.29139  ],
       [ 0.40714  ,  0.17878  ],
       [ 0.2923   ,  0.4217   ],
       [ 0.50922  ,  0.35256  ],
       [ 0.27785  ,  0.10802  ],
       [ 0.27527  ,  0.33223  ],
       [ 0.43999  ,  0.31245  ],
       [ 0.33557  ,  0.42984  ],
       [ 0.23448  ,  0.24986  ],
       [ 0.0084492,  0.13658  ],
       [ 0.12419  ,  0.33595  ],
       [ 0.25644  ,  0.42624  ],
       [ 0.4591   ,  0.40426  ],
       [ 0.44547  ,  0.45117  ],
       [ 0.42218  ,  0.20118  ],
       [ 0.49563  ,  0.21445  ],
       [ 0.30848  ,  0.24306  ],
       [ 0.39707  ,  0.44438  ],
       [ 0.32945  ,  0.39217  ],
       [ 0.40739  ,  0.40271  ],
       [ 0.3106   ,  0.50702  ],
       [ 0.49638  ,  0.45384  ],
       [ 0.10073  ,  0.32053  ],
       [ 0.69907  ,  0.37307  ],
       [ 0.29767  ,  0.69648  ],
       [ 0.15099  ,  0.57341  ],
       [ 0.16427  ,  0.27759  ],
       [ 0.33259  ,  0.055964 ],
       [ 0.53741  ,  0.28637  ],
       [ 0

In [19]:
y = data[:,-1]
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
X.T[1]

array([-0.063669,  0.29139 ,  0.17878 ,  0.4217  ,  0.35256 ,  0.10802 ,
        0.33223 ,  0.31245 ,  0.42984 ,  0.24986 ,  0.13658 ,  0.33595 ,
        0.42624 ,  0.40426 ,  0.45117 ,  0.20118 ,  0.21445 ,  0.24306 ,
        0.44438 ,  0.39217 ,  0.40271 ,  0.50702 ,  0.45384 ,  0.32053 ,
        0.37307 ,  0.69648 ,  0.57341 ,  0.27759 ,  0.055964,  0.28637 ,
        0.36879 ,  0.035148,  0.55169 ,  0.56991 ,  0.34596 ,  0.28641 ,
        0.46538 ,  0.4622  ,  0.32774 ,  0.26071 ,  0.38809 ,  0.63911 ,
        0.12007 ,  0.61666 ,  0.060408,  0.2168  ,  0.43769 ,  0.52142 ,
        0.21264 ,  0.31902 ,  1.      ,  0.59205 ,  0.6612  ,  0.86605 ,
        0.48301 ,  0.76815 ,  0.8107  ,  0.77975 ,  0.58177 ,  0.7668  ,
        0.54226 ,  0.74233 ,  0.60921 ,  0.72519 ,  0.56789 ,  0.76022 ,
        0.61857 ,  0.56224 ,  0.35025 ,  0.76921 ,  0.96764 ,  0.60865 ,
        0.92075 ,  0.66666 ,  0.56845 ,  0.7085  ,  0.63167 ,  0.80424 ,
        0.56108 ,  0.71582 ,  0.7406  ,  0.71548 , 

In [24]:
boundary_lines = trainPerceptronAlogrithm(X,y)
boundary_lines

[(array([0.55152414]), array([-2.13117352])),
 (array([3.75673789]), array([-3.59593078])),
 (array([55.12356555]), array([-27.42299077])),
 (array([-49.0767963]), array([22.27866742])),
 (array([-24.32584137]), array([11.5513429])),
 (array([-17.55313]), array([8.42633519])),
 (array([-13.66461999]), array([6.63213149])),
 (array([-12.24363032]), array([6.22133349])),
 (array([-10.39943233]), array([5.34801072])),
 (array([-9.0092606]), array([4.68969277])),
 (array([-7.92382577]), array([4.17568345])),
 (array([-7.05282428]), array([3.76321937])),
 (array([-6.33842492]), array([3.42491446])),
 (array([-5.74187677]), array([3.14241817])),
 (array([-5.23623986]), array([2.90297304])),
 (array([-4.80220388]), array([2.69743464])),
 (array([-4.42556584]), array([2.51907712])),
 (array([-4.12305068]), array([2.37817856])),
 (array([-3.85258389]), array([2.25220675])),
 (array([-3.60932889]), array([2.13890902])),
 (array([-3.38937567]), array([2.03646426])),
 (array([-3.1895291]), array([