# Regularization

<img src="images/regularization.png">
<img src="images/l1.regularization.png">
<img src="images/l2.regularization.png">

In [25]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

In [3]:
train_data = pd.read_csv('regularization_data.csv')
train_data.values

array([[-3.890120e+00, -3.751100e-01,  6.149790e+00,  4.945850e+00,
        -3.578440e+00,  6.400000e-03,  2.367628e+01],
       [ 5.097840e+00,  9.812000e-01, -2.993900e-01,  5.858050e+00,
         2.829700e-01, -2.062600e-01, -1.534590e+00],
       [ 3.903400e-01, -3.068610e+00, -5.634880e+00,  6.439410e+00,
         3.925600e-01, -7.084000e-02, -2.468670e+01],
       [ 5.847270e+00, -1.592200e-01,  1.141246e+01,  7.521650e+00,
         1.698860e+00,  2.902200e-01,  1.754122e+01],
       [-2.862020e+00, -8.433700e-01, -1.081650e+00,  6.711500e-01,
        -2.489110e+00,  5.232800e-01,  9.397890e+00],
       [-7.093280e+00, -7.233000e-02,  6.766320e+00,  1.306072e+01,
         1.287600e-01, -1.048000e-02,  1.173565e+01],
       [-7.176140e+00,  6.287500e-01, -2.899240e+00, -5.214580e+00,
        -2.703440e+00, -2.203500e-01,  4.424820e+00],
       [ 8.674300e+00,  2.099330e+00, -1.123591e+01, -5.995320e+00,
        -2.797700e+00, -8.710000e-02, -5.946150e+00],
       [-6.033240e+00, -

In [21]:
X = train_data.values[:,:-1]
X

array([[-3.890120e+00, -3.751100e-01,  6.149790e+00,  4.945850e+00,
        -3.578440e+00,  6.400000e-03],
       [ 5.097840e+00,  9.812000e-01, -2.993900e-01,  5.858050e+00,
         2.829700e-01, -2.062600e-01],
       [ 3.903400e-01, -3.068610e+00, -5.634880e+00,  6.439410e+00,
         3.925600e-01, -7.084000e-02],
       [ 5.847270e+00, -1.592200e-01,  1.141246e+01,  7.521650e+00,
         1.698860e+00,  2.902200e-01],
       [-2.862020e+00, -8.433700e-01, -1.081650e+00,  6.711500e-01,
        -2.489110e+00,  5.232800e-01],
       [-7.093280e+00, -7.233000e-02,  6.766320e+00,  1.306072e+01,
         1.287600e-01, -1.048000e-02],
       [-7.176140e+00,  6.287500e-01, -2.899240e+00, -5.214580e+00,
        -2.703440e+00, -2.203500e-01],
       [ 8.674300e+00,  2.099330e+00, -1.123591e+01, -5.995320e+00,
        -2.797700e+00, -8.710000e-02],
       [-6.033240e+00, -4.167240e+00,  2.420630e+00, -3.618270e+00,
         1.968150e+00,  1.772300e-01],
       [ 8.674850e+00,  1.482710e+00,

In [22]:
y = train_data.values[:,-1]
y

array([ 23.67628,  -1.53459, -24.6867 ,  17.54122,   9.39789,  11.73565,
         4.42482,  -5.94615, -13.11848,  -9.25647, -29.94048, -20.46775,
         7.12822,   6.05628, -32.91328,  17.75036,  -2.80277,  33.98791,
        -3.18407, -20.57366, -12.66661,  -6.5637 ,  23.19621,  13.89143,
        10.29282,  21.21512,  14.54248, -24.77918, -45.0171 , -12.63583,
         0.84415,  23.54972,  -2.2865 ,  -4.22022,  -9.10749,  -7.69059,
       -29.21246,  10.90274,   4.62178,  -7.83647,   0.06922, -16.11486,
       -38.4771 ,  20.7779 ,  14.92507,  -0.17285,  15.953  ,  -4.29743,
         4.07647,  16.50504,   9.99506, -19.94698,   6.49039,  -6.01714,
        24.56965,  27.19791,  36.21698,  -6.32623, -28.54003,  11.97581,
         9.55247,  21.83478, -13.11204, -14.74251, -18.44363,  29.20439,
        12.65607,  13.62118,  13.73746,  10.85762,  16.49896,  -8.16292,
        -6.76994,  -0.87206,  11.4835 , -23.71307,  11.82506,  13.23011,
        -0.67043,  -3.12393, -16.76419,  -7.00464, 

In [23]:
lasso_reg = Lasso()
lasso_reg.fit(X,y);

In [24]:
reg_coef = lasso_reg.coef_
reg_coef

array([ 0.        ,  2.33659619,  2.0140086 , -0.05753445, -3.91583673,
        0.        ])

In above we see that, first and last co-efficents was 0, so first and last features are removed <br>
Now we scale feature and check how it behaves <br>

In [26]:
scaler = StandardScaler()
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [27]:
X_Scaled = scaler.fit_transform(X)
X_Scaled

array([[-6.83709013e-01, -9.93560587e-02,  1.16327779e+00,
         3.92599210e-01, -1.09331803e+00, -7.53348853e-03],
       [ 9.33278816e-01,  6.87815775e-01, -1.42860566e-01,
         5.04409280e-01,  1.29811566e-01, -1.17494918e+00],
       [ 8.63713750e-02, -1.66260291e+00, -1.22344572e+00,
         5.75667670e-01,  1.64524993e-01, -4.31549231e-01],
       [ 1.06810576e+00,  2.59416440e-02,  2.22911487e+00,
         7.08319863e-01,  5.78304982e-01,  1.55052125e+00],
       [-4.98747666e-01, -3.71123636e-01, -3.01289978e-01,
        -1.31358812e-01, -7.48264857e-01,  2.82992452e+00],
       [-1.25997668e+00,  7.63706467e-02,  1.28814227e+00,
         1.38725409e+00,  8.09644316e-02, -1.00197726e-01],
       [-1.27488369e+00,  4.83261718e-01, -6.69402517e-01,
        -8.52783813e-01, -8.16155437e-01, -1.25229747e+00],
       [ 1.57670539e+00,  1.33675329e+00, -2.35781011e+00,
        -9.48480584e-01, -8.46012975e-01, -5.20809924e-01],
       [-1.06926913e+00, -2.30022306e+00,  4.080

In [28]:
lasso_reg.fit(X_Scaled,y);
reg_coef = lasso_reg.coef_
reg_coef

array([  0.        ,   3.8596924 ,   9.05021225,  -0.        ,
       -11.72692976,   0.41040086])