In [5]:
import numpy as np;

In [8]:
X = np.zeros((3,4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
print(X.dtype)

float64


In [11]:
X = np.ones((4,5))

In [13]:
print(X)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
X = np.diag((10,20,30,40))
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [19]:
X = np.full((2,3), 5)
print(X)

[[5 5 5]
 [5 5 5]]


In [20]:
x = np.arange(10)
print('x = ', x)

x =  [0 1 2 3 4 5 6 7 8 9]


In [21]:
x = np.linspace(0,25,10)
print('x = \n', x)

x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [22]:
Y = np.arange(20).reshape(4, 5)
print('Y = \n', Y)

Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [23]:
X = np.random.random((3,3))
print('X = \n', X)

X = 
 [[0.52999039 0.51610177 0.17417674]
 [0.25516822 0.1161874  0.67858801]
 [0.90606591 0.1678449  0.99488489]]


In [30]:
X = np.arange(2,33,2).reshape((4,4))
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [32]:
x = np.array([1, 2, 3, 4, 5])
print(x[0])

1


In [38]:
print(x)

[1 2 3 4 5]


In [39]:
Y = np.delete(x, [0, 4])
print(Y)

[2 3 4]


In [42]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
W = np.delete(Y, [0,2], axis=0)
print(W)

[[4 5 6]]


In [55]:
Y = np.array([[1,2,3],[7,8,9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [62]:
w = np.insert(Y,1,[4,5,6],axis=0)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
w = np.insert(Y,1,[5,6],axis=1)
print(w)

[[1 5 2 3]
 [7 6 8 9]]


In [67]:
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])
z = np.vstack((x,Y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [70]:
X = np.arange(1,21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [73]:
z = X[1:,2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [76]:
z = X[:3,:3]
print(z)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [103]:
z = X[:3,2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [104]:
X = np.arange(25).reshape(5, 5)


[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [117]:
print(X[X>10])
print(X[X<=7])
print(X[(X>10)&(X<17)])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[0 1 2 3 4 5 6 7]
[11 12 13 14 15 16]


In [120]:
X = np.arange(1,26).reshape(5,5)
print(X)
print(X[X%2!=0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [122]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [139]:
print(np.median(X, axis=1))

[ 3.  8. 13. 18. 23.]


In [151]:
X = np.ones((4,4))
X[:,1:2]=2
X[:,2:3]=3
X[:,3:4]=4
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [171]:
X = np.ones((10,10), dtype=int) * np.arange(1,11).reshape(10,1)
print(X)
Y = np.arange(1,11).reshape(10,1)
print(Y)
print(X-Y)

[[ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]
 [ 5  5  5  5  5  5  5  5  5  5]
 [ 6  6  6  6  6  6  6  6  6  6]
 [ 7  7  7  7  7  7  7  7  7  7]
 [ 8  8  8  8  8  8  8  8  8  8]
 [ 9  9  9  9  9  9  9  9  9  9]
 [10 10 10 10 10 10 10 10 10 10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [179]:
X = np.arange(20).reshape(4, 5)
indices = np.array([1,3])
print(X)
print(indices)
Y = X[indices]
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[1 3]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [186]:
X = np.random.permutation(1000)
print(X)
print(X[:601])
print(X[601:801])
print(X[801:1001])

[ 14  18 681 483 310 341 705 264 152 202 926 610 144 609 576 935 571 515
 566  74 890 809 326 115 865 821  36 564 538 136 303  10 852 133 601 388
 672 759 670 233 722 531 329 102 176 968 203 898 542  53 353 194 589 555
 104 384 607 103 473 717 993 259 244 830 358 317 449 272 556 962 688 241
 873 387 650 791 864 518 439 900  91 997 192 490 562  24 258 327 123 376
 741 409 162 551 190 186 230  42  99 448 731 743 182 819 463 689  63  62
 489 167 323 764 467 674 222 606  92 458 426 735 348 856 410 400 702 938
 445 442 999 772 560 756  47 757 907 902 328 972 298 526 370 793  84 511
 827 845 762  38 619 620 161 699 632 193 922 300 878 580 726 798 146 785
 398 481 931 455 369 450  80 724 196 925 390 729 752 521 279 528 561 579
 231 971 820 484 312 386 297 616 261 380 654 142 883 713  88 232 963 952
 441  29 464 395 522 690 527 138 813 181 593  87 816 106 884 372 399 285
 934 596 179 899  59 428  83 307 911 322  23 189 843 817 790 447 605 812
 582 712  56 512 638 875 500 583 684 271 362 824 63